### ISSUE TITLE
Reframing is broken

### ISSUE THREAD

**Issue by ArtBIT** [jtlapp/gifwrap#15]
When calling reframe with `xOffset` larger or equal to `width`, or `yOffset` larger or equal to `height`, the following error occurs:
```
(node:3647) UnhandledPromiseRejectionWarning: Error: copy exceeds width of source bitmap
    at BitmapImage.blit (./node_modules/gifwrap/src/bitmapimage.js:91:19)
    at GifFrame.reframe (./node_modules/gifwrap/src/bitmapimage.js:227:15)
    at sourceGif.frames.forEach.frame (./server.js:9:27)
    at Array.forEach (<anonymous>)
    at GifUtil.read.then.sourceGif (./server.js:7:22)
    at <anonymous>
(node:3647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
In other cases, the resulting image is empty.

**Comment by jtlapp** [comment]
Resolve in push #18. Thanks for reporting the problem. Ideally, Omggif would handle this properly for us, but for now, we'll treat it as the expected interface protocol for Omggif.
